name: 'action-test-2'
description: 'Hello'
author: 'CaiJingLong'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        echo "action path: ${{github.action_path}}"
        echo "path: ${{github.path}}"
        bash ${{github.action_path}}/check-flutter-or-dart.sh
        echo "INSTALL_FLUTTER=1" >> $GITHUB_OUTPUT
        node ${{github.action_path}}/dist/check/index.js
      id: check_env
      shell: bash
      env:
        GITHUB_PATH: ${{github.path}}
        ACTION_PATH: ${{github.action_path}}
    - run: |
        echo "pwd: $(pwd)"
        echo `the last step`
        node ${{github.action_path}}/dist/index.js
      shell: bash
    - uses: dart-lang/setup-dart@v1
      if: steps.check_env.outputs.INSTALL_DART == 1
      with:
        channel: 'stable'
    - uses: subosito/flutter-action@v2
      if: steps.check_env.outputs.INSTALL_FLUTTER == 1
      with:
        channel: 'stable'
    - run: |
        which flutter
        which dart
      name: 'check flutter or dart'
      shell: bash
