name: 'action-test-2'
description: 'Hello'
author: 'CaiJingLong'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      if: ${{ steps.check_env.outputs.is_flutter == 'true' }}
      with:
        node-version: '16'
    - run: |
        echo "action path: ${{github.action_path}}"
        echo "path: ${{github.path}}"
        bash ${{github.action_path}}/check-flutter-or-dart.sh
        node ${{github.action_path}}/dist/check/index.js
      id: check_env
      shell: bash
      env:
        GITHUB_PATH: ${{github.path}}
        ACTION_PATH: ${{github.action_path}}
    - run: |
        cd ${{github.path}}
        node ${{github.action_path}}/dist/index.js
      shell: bash
